spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 8080